//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Animals> Animals { get; set; }
        public virtual DbSet<FoodFirm> FoodFirm { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<PetCharacter> PetCharacter { get; set; }
        public virtual DbSet<PetFood> PetFood { get; set; }
        public virtual DbSet<PetGender> PetGender { get; set; }
        public virtual DbSet<PetPass> PetPass { get; set; }
        public virtual DbSet<PetTraits> PetTraits { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersPhoto> UsersPhoto { get; set; }
    }
}
