//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetCharacter
    {
        public int ID { get; set; }
        public int petID { get; set; }
        public int charID { get; set; }
    
        public virtual PetPass PetPass { get; set; }
        public virtual PetTraits PetTraits { get; set; }
    }
}
