//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetPass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PetPass()
        {
            this.PetCharacter = new HashSet<PetCharacter>();
            this.PetFood = new HashSet<PetFood>();
        }
    
        public int petID { get; set; }
        public string petname { get; set; }
        public int animalsID { get; set; }
        public int price { get; set; }
        public string birthdate { get; set; }
        public int petGenderID { get; set; }
        public string photo { get; set; }
    
        public virtual Animals Animals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PetCharacter> PetCharacter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PetFood> PetFood { get; set; }
        public virtual PetGender PetGender { get; set; }
    }
}
